# Generated by Django 2.2.17 on 2020-12-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hgfjhfkjhgfkh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jhgjhgjh', models.BigIntegerField()),
            ],
        ),
    ]
