# Generated by Django 2.2.17 on 2020-12-01 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_homepage_uytguytuyt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="uytguytuyt",
        ),
    ]
